# Generated by Django 3.1.3 on 2021-01-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/posts')),
                ('velocidad', models.CharField(max_length=255)),
                ('certificado', models.IntegerField(choices=[(0, 'No Disponible'), (1, 'Disponible')], default=1)),
                ('disponible', models.IntegerField(choices=[(0, 'No Disponible'), (1, 'Disponible')], default=1)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['producto', 'velocidad', 'certificado', 'disponible'], name='infomatica__product_a7ac24_idx'),
        ),
    ]
