# Generated by Django 3.1.3 on 2021-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomatica', '0002_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/posts')),
                ('disponible', models.IntegerField(choices=[(0, 'No Disponible'), (1, 'Disponible')], default=1)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='infomatica__product_a7ac24_idx',
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['producto', 'velocidad', 'precio', 'certificado', 'disponible'], name='infomatica__product_cab8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'nombre_cliente', 'cargo', 'disponible'], name='infomatica__empresa_5be5f4_idx'),
        ),
    ]
