# Generated by Django 3.1.3 on 2021-01-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomatica', '0003_auto_20210122_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=150)),
                ('metodoContacto', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='contacto',
            index=models.Index(fields=['nombre', 'empresa', 'telefono', 'correo'], name='infomatica__nombre_91d1d8_idx'),
        ),
    ]
